version: "3.3"

services:
  app:
    #image: library/php:8-fpm-alpine
    build:
      context: ./docker/app
    restart: always
    volumes:
      - ./docker/app/php-ini/php.ini:/usr/local/etc/php/php.ini
      - ./:/var/www/
    working_dir: /var/www
    networks:
      - laravel-bridge

  db:
    image: library/mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE_NAME=releaseDepartamentDB
    networks:
      - laravel-bridge
    ports:
      - 3306:3306
    volumes:
      - ./docker/mariadb/dbdata:/var/lib/mysql

  nginx:
    image: library/nginx:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www/
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    working_dir: /var/www
    networks:
      - laravel-bridge

networks:
  laravel-bridge:
    driver: bridge

